name: spacex_app
description: SpaceX all project in your phone.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_svg: ^1.1.6
  go_router: ^6.0.1
  json_serializable: ^6.6.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  bloc_test: ^8.2.0
  test: ^1.17.10
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svg/

